### ISSUE TITLE
Observing the StartupPipeline 

### ISSUE THREAD

**Issue by Neill-Verreynne** [Shuttle/shuttle-esb-core#2]
Hi Ebs

The modules are initialized before the StartupPipline is created. Ergo, there is no way to add any custom observers to the pipeline from a module perspective.

The create StartupPipeline and the event notification must be moved before the initialization of modules:

    var startupPipeline = new StartupPipeline(this);
    

    foreach (var module in Configuration.Modules)
    {
       module.Initialize(this);
    }
    
    Events.OnPipelineCreated(this, new PipelineEventArgs(startupPipeline));

    startupPipeline.Execute();

Thanks
Neill

**Comment by eben-roux** [comment]
Ek het dit nogal geskuif na voor die staarup pipeline oor modules dalks die startup pipeline will observe.

From: Neill-Verreynne 
Sent: Sunday, September 13, 2015 12:20 PM
To: Shuttle/shuttle-esb-core 
Subject: SPAM-LOW: [shuttle-esb-core] Observing the StartupPipeline (#2)

Hi Ebs

The modules are initialized before the StartupPipline is created. Ergo, there is no way to add any custom observers to the pipeline from a module perspective.

The create StartupPipeline and the event notification must be moved before the initialization of modules:

var startupPipeline = new StartupPipeline(this);

Events.OnPipelineCreated(this, new PipelineEventArgs(startupPipeline));

foreach (var module in Configuration.Modules)
{
module.Initialize(this);
}

startupPipeline.Execute();

Thanks
Neill

**Comment by Neill-Verreynne** [comment]
As jy gaan kyk na die huidge kode word die startup pipeline na die tyd geskep.

**Comment by eben-roux** [comment]
Oh, I see this is on GitHUb :)

The `IModule.Initialize` is where one would hook up the `_bus.Events.PipelineCreated`.  This means that moving it to where you suggest, and where it was previously, calling `Events.OnPipelineCreated(this, new PipelineEventArgs(startupPipeline));` would have no effect.

**Comment by Neill-Verreynne** [comment]
I updated the code block above, yeah the firing event should happen after the IModule.Initialize, but the create of the pipeline should be before the initialize to allow the module to hook on the pipeline created event.

**Comment by Neill-Verreynne** [comment]
Hmm, catch22 situation.

**Comment by eben-roux** [comment]
Let's give it some thought.  There should be a solution.

**Comment by Neill-Verreynne** [comment]
Thanks, it looks like it is correct.
